### ISSUE TITLE
adhesive forces between 2 cell

### ISSUE THREAD

**Issue by sinahidd3n** [UvaCsl/HemoCell#1]
Hello,
I am working with hemocell and I want to define adhesive forces between 2 different types of cells. could you please tell me how should I define forces between 2 different cells?
Thanks

**Comment by gzavo** [comment]
You can define any arbitrary force between the surface point of cells or between the cell surface and the geometry boundaries.
Take a look at 
- "HemoCellFields::HemoRepulsionForce" for an example of external repulsive force between cells and 
- "HemoCellFields::HemoBoundaryRepulsionForce" for force between cells and boundaries.

**Comment by WONGJS** [comment]
Hello
Could you tell me how to apply a time-varying force or velocity field to a cell in the Hemocell?
Thank you

**Comment by Creepermainent** [comment]
> Hello,
> I am working with hemocell and I want to define adhesive forces between 2 different types of cells. could you please tell me how should I define forces between 2 different cells?
> Thanks
