### ISSUE TITLE
Cannot validate the stretchCell case using HemoCell

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [UvaCsl/HemoCell#10]
I started to use the Hemocell example to validate Figure 4 of this paper. However, I ended up with this chart:

![thumbnail_printme](https://user-images.githubusercontent.com/15649053/133631406-ad0d8da3-a922-4e8e-b97b-36273139f425.png)
![thumbnail_result](https://user-images.githubusercontent.com/15649053/133631408-4c84dec4-5f05-474a-b6d0-f0343a111eb0.png)

As you can see further I increase the value of force, my values in D_max would not match paper data. I have not changed any parameters in this case and I wonder why that happens. I also continued the simulation for 650K iterations but it didn't change that much. Do you have any comments about this?

Thanks,
Mojtaba

**Comment by MaxvdKolk** [comment]
Hi Mojtaba,

The current definition of the RBC mechanics are slightly stiffer compared to the originally published values. This provides improved stability when running simulations with (high) shear flows, while maintaining similar force-displacement curves matching with the validated data set. 

The various stiffnesses of the RBC are defined in [`mechanics/rbcHighOrderModel.cpp`](https://github.com/UvaCsl/HemoCell/blob/master/mechanics/rbcHighOrderModel.cpp). To get closer to the original curves, you could modify the bending stiffness from the current `0.055` ([line 157](https://github.com/UvaCsl/HemoCell/blob/f672f11e5f80070285e222d7b4a6abaa82879253/mechanics/rbcHighOrderModel.cpp#L157)), to `2.467` (or more precisely `(pi/2)^2`).

Note that the current set of parameters are not unique, so various combinations of stiffnesses will show force-displacement curves matching the validation data set. In the next release will add additional documentation to clarify these constants and the resulting force-displacement curves.

**Comment by mojtabaAmiraslanpour** [comment]
> Hi Mojtaba,
> 
> The current definition of the RBC mechanics are slightly stiffer compared to the originally published values. This provides improved stability when running simulations with (high) shear flows, while maintaining similar force-displacement curves matching with the validated data set.
> 
> The various stiffnesses of the RBC are defined in [`mechanics/rbcHighOrderModel.cpp`](https://github.com/UvaCsl/HemoCell/blob/master/mechanics/rbcHighOrderModel.cpp). To get closer to the original curves, you could modify the bending stiffness from the current `0.055` ([line 157](https://github.com/UvaCsl/HemoCell/blob/f672f11e5f80070285e222d7b4a6abaa82879253/mechanics/rbcHighOrderModel.cpp#L157)), to `2.467` (or more precisely `(pi/2)^2`).
> 
> Note that the current set of parameters are not unique, so various combinations of stiffnesses will show force-displacement curves matching the validation data set. In the next release will add additional documentation to clarify these constants and the resulting force-displacement curves.

Thank you @MaxvdKolk for your response!

1. **Stiffness of RCB:** I tried that and the results were closer to the chart:

![printme](https://user-images.githubusercontent.com/15649053/134402281-12c7d97c-e534-48d4-9b58-1b9ef9438657.png)

2. **Resolution:** As another approach, I tried increasing the resolution of the LB field and my results were closer for the F = 37 and 187 pN cases (not for the 87 pN case, do not know why) but I am not sure if I have done it correctly. When the simulation starts I got some Sanity check warnings that tell me values are wrong.

`(HemoCell) (SanityCheck) WARNING: Fluid dx is not 5e-7 but 2.5e-07 This is unvalidated!`

I also tried increasing the resolution for RCB itself so both get increased proportionally but got more sanity warnings!
So is there any right way to do it?

3. Also I have contacted "Gábor Závodszky" and he told me that there are some additional parameters that enforce constant volume, or surface area, etc. It has been done for numerical stability and stuff. So do you know where I can change them? and what are the correct values for them? Actually, I see that while running surface and volume of the RCB are changing. So I cannot understand this argument.

4. Do you have any more suggestions? Any more parameters to change?

Thanks!
Mojtaba

**Comment by MaxvdKolk** [comment]
Hi Mojtaba,

This looks very close :+1:

> I also tried increasing the resolution for RCB itself so both get increased proportionally but got more sanity warnings!
So is there any right way to do it?

It might be that Gabor can provide more insight on the exact settings of these resolutions. As far as I know, the sanity checks will report warnings when using a different resolution `dx` than `5e-7`, as (most of) the validations have been evaluated using that specific resolution. So for different resolutions, you might need to carefully run validation tests to see if the desired behaviour is still maintained throughout the simulations. 

> 3. Constant Volume and Surface

The parameters are described in section 2.2 of the publication and are implemented within the cell mechanics model (see [rbcHigherOrderModel.cpp](https://github.com/UvaCsl/HemoCell/blob/master/mechanics/rbcHighOrderModel.cpp)). In release `2.3` those constants are given directly in the implementation, for instance:

- maximum surface area change: [line 79](https://github.com/UvaCsl/HemoCell/blob/f672f11e5f80070285e222d7b4a6abaa82879253/mechanics/rbcHighOrderModel.cpp#L79)
- maximum volumetric change: [line 104](https://github.com/UvaCsl/HemoCell/blob/f672f11e5f80070285e222d7b4a6abaa82879253/mechanics/rbcHighOrderModel.cpp#L104)
- maximum bending force: [line 157](https://github.com/UvaCsl/HemoCell/blob/f672f11e5f80070285e222d7b4a6abaa82879253/mechanics/rbcHighOrderModel.cpp#L157)
- maximum stretch length: [line 181](https://github.com/UvaCsl/HemoCell/blob/f672f11e5f80070285e222d7b4a6abaa82879253/mechanics/rbcHighOrderModel.cpp#L181)

As the combination of the validated parameters are not necessarily unique, you can find different combinations of these parameters that result in force-displacement curves that match the experimental data more/less closely. You might find different combinations of these parameters that fit better with the application in mind. For instance, the change to the bending stiffness (as compared to the originally published values) still provide validated behaviour, while being much more (numerically) stable when undergoing high shear flows. 

Note: we are currently preparing release `2.4` which features more extensive documentation and which refactors these constants. In the new version, these will be defined explicitly under `config/constant_defaults.h` as 

```cpp
// Note: these are already expressed as their squared value
constexpr T MaxCellVolumetricChange = 0.01;
constexpr T MaxCellSurfaceAreaChange = 0.09;
constexpr T MaxCellBendingAngle = 0.0555;
constexpr T MaxCellPersistenceLength = 9.0;
```
which will make it easier for you to change these numbers in one location and observe the effects on the force-displacement curves. Hopefully this should be available somewhere next week.

> Actually, I see that while running surface and volume of the RCB are changing. So I cannot understand this argument

Yes, there is some change of surface and volume possible of the RBC. For instance, you can take a look at the stretch response of the cell (section 2.2, the first bullet point and equation). The constant there `tau_l` corresponds to one of the constants defined in the code. Once the stretch reaches a certain amount, the force term will steeply increase and prevent further extension of the cell. You can think of these as barrier-like functions preventing too much change in either stretch, bending, surface area, or volume. Some change _is_ possible, but bounded by these constants.

> Do you have any more suggestions? Any more parameters to change?

You could investigate different values of the used time step (in this example `dt = 1e-7` I believe), although I am not sure how bit of an influence that makes for this specific validation case. There are also parameters to set how often the particle model and fluid models are updated (`stepMaterialEvery`, `stepParticleEvery`), however for this validation case updating every iteration (default behaviour) should be fine.

Also make sure that you observe a steady state (similar to the second figure in your first post) when playing around with the different parameters. it might be that you require more/less when trying different sets of constants.

**Comment by mojtabaAmiraslanpour** [comment]
Thank you @MaxvdKolk to answer my questions thoroughly.

1. I mentioned that tau_bend = pi/6 in the paper but you suggested putting (pi/2)^2. Are there any reasons? I expect to get the same results in the paper by setting the same values and that's why I am not trying my own combinations of parameters.

2. The other thing I did not see a mesh dependency study in the paper (or maybe I missed it?). So I am not sure if my resolution is the same as the one in the paper.

Best

**Comment by MaxvdKolk** [comment]
Hi Mojtaba, 

Agreed, not completely sure why the publication mentions `tau_bend = pi/6`. The code contained `pi/2`. Following the expression for the minimal representable curvature `r_min = L_0/2 * sin(tau_bend / 2)` with using here `L_0 = 0.5` micron and `tau_bend = pi/2`, we find `r_min = 0.176` micron.  This is similar to the minimal curvature mentioned in the paper (0.18 micron). I did not notice the `pi/6` mentioned in that paragraph.. and I have to apologise for not knowing if either I am misinterpreting these equations and the derivations or that there is a typo in the publication.. 

Note that the constants are given directly as their squared values. In all these force equations they will only appear squared, so we only store `tau_bend^2` rather than `tau_bend` itself. 

> The other thing I did not see a mesh dependency study in the paper (or maybe I missed it?). So I am not sure if my resolution is the same as the one in the paper.

As far as I am aware, the study has been done for a specific configuration, using `dx = 0.5` micron for the lattice grids. Using other resolutions should also work, although you might to reevaluate these curves to be completely sure. The default configurations of the stretching cell example match with the values used during the numerical experiments for the validation.

**Comment by mojtabaAmiraslanpour** [comment]
Good points @MaxvdKolk!
I was not paying attention to the squared values of the constants! I corrected them (used `tau_bend = pi/2`), used `dx=0.5e-6`, and ran for a higher number of iterations (420'000), and here is what I got:

![results](https://user-images.githubusercontent.com/15649053/134978868-133a9905-29f7-4a16-ab4d-78a25786efeb.png)

Overall better results than the other two.

1. The one thing that I cannot understand now is the initial volume value. It is given as an input inside the RCB.xml file but it actually is imported from the STL file, right? I put 71 um^3 for the volume value (which is mentioned in the paper but was 90 um^3 by default) but I get a value of 81 um^3 in the simulation log file.

2. Also, the membrane viscosity `eta_m` is set to be zero. is this correct?

Best,
Mojtaba

**Comment by gzavo** [comment]
Hi @mojtabaAmiraslanpour,
for your last two questions:
1) It is also possible to import cell shapes from STL, but in all the examples RBCs and PLTs are generated at runtime by the following algorithm: a) we generate a sphere with homogeneous surface vertex distribution, b) we subdivide the sphere to get to the requested vertex count, c) we project the surface vertices to the shape of the cell (e.g., biconcave for RBCs).
This allows us to change the number of vertices from the config file, which is not possible using an STL.
The volume is a tricky questions, because we have two types of it: (1) the mesh volume, which is used for instance at stretching tests, (2) the larger effective volume which is used for cell collision interaction.
If you generate the cell, and not load it from STL, the volume depends on the radius you give in the xml.
E.g., r = 3.91e-6  =>  V_mesh = 81.116 um3; V_effective = 97.687 um3 
The effective volume happens due to the fluid-structure coupling. The immersed boundary method uses interpolation kernels (of size 0.5 um by default in HemoCell), that increases the outer radius of the cell by 0.25 um to an effective radius of 4.16e-6 um (which leads to the larger volume). Technically it means that two cells already interact when their IBM kernels start to overlap, which happens before their actual meshes touch. So when calculating bulk blood flow properties (e.g., viscosity) the effective volume yields the correct predictions. On the other hand if you are measuring the deformation of a single cell, you want the mesh radius instead of the effective interaction radius.
2) Yes, it is turned off by default, because it causes very little difference in most cases, however it forces significantly smaller time-steps. If you need very accurate deformation velocities you can turn it on (i.e. give it a non-zero value). Also note that it is different from cell viscosity.

Hope these helped!

**Comment by mojtabaAmiraslanpour** [comment]
Thank you @gzavo! It did help a lot. So if we take a look at the RCB.xml file:
```
...
    <radius> 3.91e-6 </radius> <!-- Radius of the RBC in [ 3.96 um] -->
    <Volume> 71 </Volume> <!-- Volume of the RBC in µm³ -->
...
```

We see there are both _radius_ and _volume_ defined here. What you say is that only the _radius_ is playing a role in the current examples and not the _volume_. So Why do a have _volume_ as a parameter in here after all?

**Comment by gzavo** [comment]
You're right @mojtabaAmiraslanpour, I forgot to answer that part.
It is used for some density calculation in the output. The reason is that the mesh volume is not the same as the effective volume, so you can supply the desired volume value.

**Comment by mojtabaAmiraslanpour** [comment]
Hello all,
Right now I am trying to validate oneCellShear and pipeFlow cases which are mentioned in the paper.
For the pipeflow case, I see that we need to put Re as an input so it can calculate the plasma velocity. I can't find any Re mentioned in the paper. The only thing I noted is the caption of figure 8 which says they used an average velocity of 1.5 cm/s which gives a Re=1.74 for D=128 um case. However, we know that velocity is not the same in all cases. So where can I find that?

Thanks!

**Comment by mojtabaAmiraslanpour** [comment]
For the case of oneCellShear example, I got something like this for DI-iter chart: (the shear rate is set to be 111 s^-1)
![Screenshot from 2021-10-04 07-51-07](https://user-images.githubusercontent.com/15649053/135883845-026bfe1b-61a0-4201-b257-1708b99552f8.png)

So it gives an average DI value of about 13% which is not in agreement with figure 5 in the paper. When I increase tau_bening from 0.055 to 2.467 the cell is distorted and not reaching a steady or periodic state. Any comments on that?

**Comment by mojtabaAmiraslanpour** [comment]
@gzavo Thank you for the paper!
Is this method already implemented in the Hemocell? If yes, where can I set the viscosity ratio (Λ) inside the code to see the effects?

@MaxvdKolk I am already running the cases with larger domains. Can this case run in parallel (by changing the code)? It actually takes so much time to solve on a single core. Besides, I am not changing the domain size in x and z-directions due to the periodic BC. Is that correct?

Also, I want to know if you have used Lees-Edwards BC in the oneCellShear case since it actually eliminates wall effects and we can run it with a small domain as well. Right? If this is the case is not using that, are there any examples that use it?

Best

**Comment by MaxvdKolk** [comment]
> I am already running the cases with larger domains. Can this case run in parallel (by changing the code)? It actually takes so much time to solve on a single core. Besides, I am not changing the domain size in x and z-directions due to the periodic BC. Is that correct?

Yes, as far as I am aware this case can be evaluated in parallel without difficulties. You can run the case normally with, for example, `mpirun -n $nproc ./oneCellShear config.xml` and set `$nproc` to the number of cores you desire (it will not perform better with more cores than hardware cores available in your system). Keeping the other dimensions the same size, should be OK. The boundary effects that influence the deformation index, mostly arise from the surfaces at which the shear velocity is prescribed. 

> Also, I want to know if you have used Lees-Edwards BC in the oneCellShear case since it actually eliminates wall effects and we can run it with a small domain as well. Right? If this case is not using that, are there any examples that use it?

The  `oneCellShear` example does _not_ use Lees-Edwards type boundary conditions. The example simply prescribes the velocity field on the opposing surfaces between which the shear flow is desired. The prescribed velocity magnitude is then based on the user-specified shear rate and the dimensions of the domain. It should be possible to utilise Lees-Edwards boundary conditions for this example. However, we do not yet provide a detailed example of the such boundary conditions as they are still an _experimental_ feature and undergoing ongoing development. You are, of course, free to explore the Lees-Edwards functionality in the source code and try to use its functionalities. However, my suggestion would be to simply use the prescribed velocity on a (slightly) enlarged domain until we provide a documented example describing the Lees-Edwards functionality in detail.

> It actually works and shows the largest diameter for cell 0. But when I am trying to do it for other cid's it gives me 0 value. Am I doing something wrong here?

This might be that you are accessing cell IDs that are not present in the actual simulations. This could be caused by using a `*.pos` file in which some cells are truncated, i.e. they are removed during initialisation as they overlap with the outer boundary of the simulation domain. In that case, the cell IDs might not be a complete range of integers and could skip one or more values. 

You could, for instance, loop over all `key,value` pairs present in the `info_per_cell` map and access the `stretch` value for the individual cells to compute their deformation indices, something like:

```cpp
while (hemocell.iter < tmax) {
    hemocell.iterate()
    
    ...

    CellInformationFunctionals::calculateCellStretch(&hemocell);

    // Loop over (ID, cell_info) pairs in the `info_per_cell` map
    for (auto const& cell_info: CellInformationFunctionals::info_per_cell) {
        auto diameter = (cell_info.second.stretch)/(1e-6/param::dx);
        // Note: D0 is a given constant, see the `oneCellShear` example.
        auto relative_diameter = (diameter/D0)*(diameter/D0);                                                                                      
        auto DI = (relative_diameter - 1.0)/(relative_diameter + 1.0)/100.0;
        hlog << "\n\tDeformation index:" << DI;
    }

    CellInformationFunctionals::clear_list();
}
```

You might need to do some additional post-processing on the obtained `DI` values, depending on your the values you desire to compute (average, max/min, etc).

**Comment by mojtabaAmiraslanpour** [comment]
Thanks,

1. The thing is when the cell drifts, it eventually reaches the boundary in x directions and is omitted. So then I would get a DI value of -100%. It happens so fast in high shear rates and won't let me see the steady-state DI value. Of course, I can scale the domain in the x-direction to delay it but it would increase the computational effort. Apparently, the cell cannot be re-entered into the domain when it is out.
2. I am trying to run oneCellShear case with interior viscosity ON and try to compile it with the relevant flag. But I get this error when compiling:
```
  Manually-specified variables were not used by the project:

    INTERIOR_VISCOSITY
```
Are there any workarounds for this?

**Comment by MaxvdKolk** [comment]
> The thing is when the cell drifts, it eventually reaches the boundary in x directions and is omitted. 

Yes, eventually the cell might drift outside of the simulation domain and will indeed be deleted if you do not opt for periodicity. You can of course, as you mentioned, increase the domain in `x`-direction to such an extend that the cell remains within the domain for the full simulation. However, this does become computationally inefficient when there is significant velocity in `x`-direction. Alternatively, you might choose to consider periodic boundary conditions along the `x`-direction. Doing so will ensure the cell is reinserted in the simulation domain when leaving through the periodic boundary. To enable this you can include the following (c.f. [`examples/parachuting.cpp`](https://github.com/UvaCsl/HemoCell/blob/master/examples/parachuting/parachuting.cpp#L103))

```cpp
HemoCell hemocell(argv[1], argc, argv);
// ...
hemocell.setSystemPeriodicity(0, true);
// ...
```

> Are there any workarounds for this?

No workarounds should be required to enable interior viscosity in your (custom) example cases. If you want to include these effects, you can do so by enabling this feature in the `CMakeLists.txt` definition for your example. By default (assuming you started from [`examples/template/CMakeLists.txt`](https://github.com/UvaCsl/HemoCell/blob/master/examples/template/CMakeLists.txt)), this links the example's `.cpp` file with the default hemocell (`"${PROJECT_NAME}"`) library, which you might want to change to `${PROJECT_NAME}_interior_viscosity"`. Then, CMake will ensure your example is linked with the corresponding hemocell library including interior viscosity.

You might want to compare the following configuration for an example without and with interior viscosity:

```
examples/parachuting/CMakeLists.txt
examples/cellCollision_interior_viscosity/CMakeLists.txt
``` 

and the related section of our documentation [`compiling-examples-with-special-features`](https://www.hemocell.eu/user_guide/Case.html#compiling-examples-with-special-features).

**Comment by mojtabaAmiraslanpour** [comment]
@MaxvdKolk Just to make sure, I see there is a line of code inside the cellCollision_interior_viscosity case that reads:

`hemocell.setInteriorViscosityTimeScaleSeperation((*cfg)["sim"]["interiorViscosity"].read<int>(),(*cfg)["sim"]["interiorViscosityEntireGrid"].read<int>());`

So don't I need to add this line to my custom example case? And also can you explain a bit about the two parameters being read here. i.e `interiorViscosity` and `interiorViscosityEntireGrid`?

I see that we set `viscosityRatio` in the RBC.xml file.

**Comment by mojtabaAmiraslanpour** [comment]
I am having a problem setting the Hematocrit value and getting the correct RBC.pos and PLT.pos files. I compare my results to the available .pos files in `pipeflow/initial_states`.
I use the `packCells `tool to reproduce the D64_Ht21 case. So here is what I do:

`packcells 128 64 64 -h 0.21 -r`

And what I get is:
RBC: 1135

But I should get 1832. I found that inside the `packCells `code, the volume of a single RBC is put to be `97 µm^3`:

`double rbcVolNominal = 81.0; // This is set to match the model used in HemoCell! `

I don't know what it means by the comment.

Now, from the `oneCellShear` case I find the reported RBC volume (at initial state) to be `81.1 µm^3`. So when I use that I get 1357 which I am still far away from what I should get.

By running the `pipeFlow `case with the initial_state .pos files, I get fairly good results when compared to the paper. That is why I am trying to reproduce them using the `packCells `tool.

**Comment by mojtabaAmiraslanpour** [comment]
@MaxvdKolk Thank you,

Regarding the hematocrit value, actually it is about the removed particles on the pipe surface (cut-through particles) and not the particles near the corners (since hematocrit is an intensive property and is not dependent on the size of the domain). So I was working to get the real-time hematocrit value in the solver and started to write the code. However, I mentioned that the number of cells reported by `getNumberOfCellsFromType(&hemocell, "RBC");` is not the same as the range that I am looping on:

`for (auto const& cell_info: CellInformationFunctionals::info_per_cell) {
    ...
	}`
This confused me. The idea is to compute the volume of the whole RBC's and divide it by the volume of the domain. This is actually how the packCells tool works, as I validated it using a simple excel worksheet.

Finally, I can easily set the -h value in packCells and see the result as solver runs.

**Comment by mojtabaAmiraslanpour** [comment]
Just found out that when I run the solver with one processor, I get the correct number of cells for both functions. I don't know how to achieve this when running in parallel.

**Comment by MaxvdKolk** [comment]
> Regarding the hematocrit value, actually it is about the removed particles on the pipe surface (cut-through particles) and not the particles near the corners

Sure, I was hinting at the remaining domain outside of the pipe surface, towards the corners of the square cross-section.

The total cell counts should be OK when running with any number of processors, as those are gathered and reduced from all domains into a single, total cell count. However, the `info_per_cell` class itself is not threadsafe, as mentioned in the comments near the class defined in `helper/cellInfo.h`. So, when iterating on multiple threads simultaneously, you might see unexpected behaviour. If you want to perform specific operations across atomic blocks (threads) you might want to implement a specific `Functional` as the parallelisation is then handled by the (underlying) library.

**Comment by mojtabaAmiraslanpour** [comment]
@MaxvdKolk I am struggling to implement the new `Functional `to handle the parallelization. Can you help me find a simple way to find the average volume of all RBCs when I am running in parallel? I do not want to go deep into the code at this stage.

I am just doing this to find the exact hematocrit value at each time step since I am not able to validate the `pipeflow `case results. I am thinking the hematocrit value is not correct. All other parameters are the same as the paper.

**Comment by MaxvdKolk** [comment]
Would it be sufficient to use the total cell count to determine the hematocrit value for the pipe flow problem? For instance use the cell count from `CellInformationFunctionals::getTotalNumberOfCells(&hemocell)` and determine an estimated hematocrit value considering the pipe's volume?

Or do you aim to evaluate the hematocrit using the deformed cells' volumes?

**Comment by mojtabaAmiraslanpour** [comment]
> Or do you aim to evaluate the hematocrit using the deformed cells' volumes?

I have estimated the hematocrit value by the method you mentioned and I still don't get the correct value.
I actually want to include deformed cell volumes as well.
