### ISSUE TITLE
Increment version string

### ISSUE THREAD

**Issue by ivan-pi** [UvaCsl/HemoCell#52]
https://github.com/UvaCsl/HemoCell/blob/cf106f34aa015ee28d8de32ccd440ff3fb5abb16/CMakeLists.txt#L5

According to the commit messages, HemoCell is currently at v2.5.

**Comment by gzavo** [comment]
Right, good catch. This and the internal version (below) has been fixed now in the main repo. It will be mirrored here with the next 2.6 version.
https://github.com/UvaCsl/HemoCell/blob/cf106f34aa015ee28d8de32ccd440ff3fb5abb16/config/constant_defaults.h#L34-L35
