### ISSUE TITLE
Cannot compile, hemocell.h: No such file or directory

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [UvaCsl/HemoCell#8]
Hello all.

I was trying to go through the guide and compile my desired case but I failed. I compiled Hemocell itself using

mkdir build
cd build
cmake ../
make

but whenever I want to compile any cases, "oneCellShear" in my case, compilation shops, saying that

hemocell.h: No such file or directory

So the CMakeLists are not set up or I am doing something wrong?

Thanks,
Mojtaba

**Comment by mojtabaAmiraslanpour** [comment]
Ok, I see there is a compile.sh in each case. It is highly recommended to mention this in the user guide so the new users can compile the code faster. I almost put about 3-4 hours understanding that.

Thanks

**Comment by MaxvdKolk** [comment]
Hi Mojtaba,

Thanks for bringing this under our attention. The hosted documentation (`v2.2`) are unfortunately slightly behind the current version `v2.3` (and upcoming developments). Next releases feature extended documentation that hopefully clarify the compilation of HemoCell and the examples. 

You might already browse the (party) updated documentation within the repository: [compiling-hemocell-from-source](https://github.com/UvaCsl/HemoCell/blob/master/doc/user_guide/QuickStart.rst#compiling-hemocell-from-source).
