### ISSUE TITLE
Any forum to talk about the problems?

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [UvaCsl/HemoCell#9]
Hi, is there any forum that we may discuss the problems we encounter?
Should we post our issues here only?

Bests
Mojtaba

**Comment by MaxvdKolk** [comment]
At the moment, there is no HemoCell-specific forum for such discussions. If you encounter problems with the library, of have other questions, feel free to raise the issues here. Alternatively, you can directly contact the developers/maintainers, see contact information [here](https://www.hemocell.eu/user_guide/index.html#acknowledgments).

We will do our best to help out with any issues or questions. However, as we (currently) only push newly tagged version to this repository, any new features or bug fixes might have some delay before they become available.

**Comment by mojtabaAmiraslanpour** [comment]
Ok, Thanks.
